# CMake generated Testfile for 
# Source directory: /home/dell/projects/calamares/src/modules
# Build directory: /home/dell/projects/calamares/build/src/modules
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(config-bootloader "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/bootloader/bootloader.conf")
add_test(config-contextualprocess "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/contextualprocess/contextualprocess.conf")
add_test(config-displaymanager "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/displaymanager/displaymanager.conf")
add_test(config-dummycpp "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/dummycpp/dummycpp.conf")
add_test(config-dummypython "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/dummypython/dummypython.conf")
add_test(config-dummypythonqt "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/dummypythonqt/dummypythonqt.conf")
add_test(config-finished "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/finished/finished.conf")
add_test(config-fsresizer "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/fsresizer/fsresizer.conf")
add_test(config-fstab "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/fstab/fstab.conf")
add_test(config-grubcfg "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/grubcfg/grubcfg.conf")
add_test(config-initcpio "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/initcpio/initcpio.conf")
add_test(config-interactiveterminal "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/interactiveterminal/interactiveterminal.conf")
add_test(config-keyboard "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/keyboard/keyboard.conf")
add_test(config-license "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/license/license.conf")
add_test(config-locale "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/locale/locale.conf")
add_test(config-luksopenswaphookcfg "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/luksopenswaphookcfg/luksopenswaphookcfg.conf")
add_test(config-machineid "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/machineid/machineid.conf")
add_test(config-mount "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/mount/mount.conf")
add_test(config-netinstall "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/netinstall/netinstall.conf")
add_test(config-openrcdmcryptcfg "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/openrcdmcryptcfg/openrcdmcryptcfg.conf")
add_test(config-packages "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/packages/packages.conf")
add_test(config-partition "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/partition/partition.conf")
add_test(config-plasmalnf "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/plasmalnf/plasmalnf.conf")
add_test(config-plymouthcfg "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/plymouthcfg/plymouthcfg.conf")
add_test(config-preservefiles "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/preservefiles/preservefiles.conf")
add_test(config-rawfs "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/rawfs/rawfs.conf")
add_test(config-removeuser "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/removeuser/removeuser.conf")
add_test(config-services-openrc "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/services-openrc/services-openrc.conf")
add_test(config-services-systemd "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/services-systemd/services-systemd.conf")
add_test(config-shellprocess "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/shellprocess/shellprocess.conf")
add_test(config-tracking "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/tracking/tracking.conf")
add_test(config-umount "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/umount/umount.conf")
add_test(config-unpackfs "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/unpackfs/unpackfs.conf")
add_test(config-users "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/users/users.conf")
add_test(config-webview "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/webview/owncloud.conf")
add_test(config-webview-1 "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/webview/webview.conf")
add_test(config-welcome "/home/dell/projects/calamares/build/test_conf" "/home/dell/projects/calamares/build/src/modules/welcome/welcome.conf")
subdirs("contextualprocess")
subdirs("dracutlukscfg")
subdirs("dummycpp")
subdirs("finished")
subdirs("fsresizer")
subdirs("interactiveterminal")
subdirs("keyboard")
subdirs("license")
subdirs("locale")
subdirs("netinstall")
subdirs("partition")
subdirs("plasmalnf")
subdirs("preservefiles")
subdirs("shellprocess")
subdirs("summary")
subdirs("tracking")
subdirs("users")
subdirs("webview")
subdirs("welcome")
